version: 2

models:
  - name: stg_LineItem
    config:
      materialized: table
    tests:
      # - dbt_utils.unique_combination_of_columns:
      #     combination_of_columns:
      #       - l_orderkey
      #       - l_linenumber
      - extended_unique:
          columns:
            - l_orderkey
            # - l_linenumber
    columns:
      - name: l_orderkey
        tests:
          - not_null