version: 2

sources:
  - name: snowflake_sample
    database: snowflake_sample_data
    schema: tpch_sf10
    config:
      enabled: true
    tables:
      - name: LINEITEM
      - name: REGION
      - name: NATION
      - name: PARTSUPP
      - name: CUSTOMER
      - name: ORDERS
      - name: PART
      - name: SUPPLIER
  - name: test_data
    database: raw
    schema: source
    tables:
      - name: Inc
      - name: Status_Table
      - name: scd
